services:
  pyspark-notebook:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    volumes:
      - ./src:/home/jovyan/src
      - ./data:/home/jovyan/data
    working_dir: /home/jovyan
    env_file:
      - .env
