services:
  pyspark-nbdiy:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    volumes:
      - /Users/kevinlou/Studio/Statistics-and-Data-Analysis-in-Python:/home/jovyan/notebooks/
      # - ./data:/home/jovyan/data
    working_dir: /home/jovyan
    # env_file:
    #   - .env

